# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rrustbio_wrappers", use_symbols = TRUE, package_name = "rrustbio")

#' @docType package
#' @usage NULL
#' @useDynLib rrustbio, .registration = TRUE
NULL

GFF <- new.env(parent = emptyenv())

GFF$from_file <- function(path) .Call(wrap__GFF__from_file, path)

GFF$as_dataframe <- function() .Call(wrap__GFF__as_dataframe, self)

#' @export
`$.GFF` <- function (self, name) { func <- GFF[[name]]; environment(func) <- environment(); func }

#' @export
`[[.GFF` <- `$.GFF`

