# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_r-rust-bio_wrappers", use_symbols = TRUE, package_name = "r-rust-bio")

#' @docType package
#' @usage NULL
#' @useDynLib r-rust-bio, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

